# Generated by Django 5.2.6 on 2025-09-29 19:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('coords', models.CharField(max_length=100)),
                ('ocupado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('assento_id', models.CharField(max_length=50)),
                ('assento_label', models.CharField(max_length=50)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('pdf_arquivo', models.FileField(blank=True, upload_to='tickets/')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('assento_id',), name='unique_assento_vendido')],
            },
        ),
    ]
